version: '3.7'

services:
   tunnel-1194:
      image: c6supper/galaxy-tunnel:${TUNNEL_TAG}
      container_name: galaxy-tunnel-1194
      privileged: true
      network_mode: ${APP_NETWORK_MODE}
      restart: ${APP_RESTART_POLICY}
      environment:
         RUN_AFTER_SIDECAR: 'no'
         OVPN_PORT: 1194
         OVPN_PROTO: tcp
         OVPN_IP_POOL: 10.0.0.0
         OVPN_TLS_AUTH: ta.key
         OVPN_CA: ca.crt
         OVPN_CERT: server1.crt
         OVPN_KEY: server1.key
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}

   tunnel-1195:
      image: c6supper/galaxy-tunnel:${TUNNEL_TAG}
      container_name: galaxy-tunnel-1195
      privileged: true
      network_mode: ${APP_NETWORK_MODE}
      restart: ${APP_RESTART_POLICY}
      environment:
         RUN_AFTER_SIDECAR: 'no'
         OVPN_PORT: 1195
         OVPN_PROTO: udp
         OVPN_IP_POOL: 10.13.13.0
         OVPN_TLS_AUTH: longterm/ta.key
         OVPN_CA: longterm/ca.crt
         OVPN_CERT: longterm/server2.crt
         OVPN_KEY: longterm/server2.key
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}

   tunnel-1196:
      image: c6supper/galaxy-tunnel:${TUNNEL_TAG}
      container_name: galaxy-tunnel-1196
      privileged: true
      network_mode: ${APP_NETWORK_MODE}
      restart: ${APP_RESTART_POLICY}
      environment:
         RUN_AFTER_SIDECAR: 'no'
         OVPN_PORT: 1196
         OVPN_PROTO: udp
         OVPN_IP_POOL: 10.14.14.0
         OVPN_TLS_AUTH: longterm/ta.key
         OVPN_CA: longterm/ca.crt
         OVPN_CERT: longterm/server3.crt
         OVPN_KEY: longterm/server3.key
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}

   nginx:
      image: c6supper/galaxy-nginx:${NGINX_TAG}
      container_name: galaxy-nginx
      network_mode: ${APP_NETWORK_MODE}
      restart: ${APP_RESTART_POLICY}
      environment:
         GALAXY_TUNNEL_HOST: ${APP_HOST}
         GALAXY_CLIENT_HOST: ${APP_HOST}
      depends_on:
         - client
         - tunnel-1194
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}

   client:
      image: c6supper/galaxy-client:${CLIENT_TAG}
      container_name: galaxy-client
      network_mode: ${APP_NETWORK_MODE}
      restart: ${APP_RESTART_POLICY}
      depends_on:
         - postgres
      environment:
         GALAXY_GUACD_HOST: ${APP_HOST}
         GALAXY_POSTGRES_HOST: ${APP_HOST}
         GALAXY_POSTGRES_DB: ${CLIENT_DB}
         GALAXY_POSTGRES_USER: ${APP_POSTGRES_USER}
         GALAXY_POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD}
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}

   guacd:
      image: c6supper/galaxy-guacd:${GUACD_TAG}
      container_name: galaxy-guacd
      network_mode: ${APP_NETWORK_MODE}
      restart: ${APP_RESTART_POLICY}
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}

   postgres:
      image: c6supper/postgres:${POSTGRES_TAG}
      container_name: galaxy-postgres
      network_mode: ${APP_NETWORK_MODE}
      restart: ${APP_RESTART_POLICY}
      environment:
         POSTGRES_USER: ${APP_POSTGRES_USER}
         POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD}
         POSTGRES_DB: ${APP_POSTGRES_DB}
      volumes:
         - type: bind
           source: ${POSTGRES_DATA_VOLUME}
           target: /var/lib/postgresql/data
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}

   keycloak:
      image: jboss/keycloak:${KEYCLOAK_TAG}
      container_name: galaxy-keycloak
      network_mode: ${APP_NETWORK_MODE}
      restart: ${APP_RESTART_POLICY}
      environment:
         KEYCLOAK_USER: ${KEYCLOAK_USER}
         KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
         POSTGRES_USER: ${APP_POSTGRES_USER}
         POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD}
         POSTGRES_DB: ${KEYCLOAK_DB}
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}
