{{- define "common.service" -}}
{{- $common := dict "Values" .Values.common -}} 
{{- $noCommon := omit .Values "common" -}} 
{{- $overrides := dict "Values" $noCommon -}} 
{{- $noValues := omit . "Values" -}} 
{{- with merge $noValues $overrides $common -}}
apiVersion: v1
kind: Service
{{ template "common.metadata" . }}
spec:
  type: {{ .Values.service.spec.type }}
  {{- if .Values.service.spec.clusterIP }}
  clusterIP: {{ .Values.service.spec.clusterIP }}
  {{- else }}
  clusterIP: None
  {{- end }}
  {{- if .Values.service.spec.sessionAffinity }}
  sessionAffinity: {{ .Values.service.spec.sessionAffinity }}
  {{- else }}
  sessionAffinity: None
  {{- end }}
  ports:
    {{ toYaml .Values.service.spec.ports | nindent 4 | trim }}
  selector:
    app.kubernetes.io/name: {{ include "common.name" . }}
    app.kubernetes.io/instance: {{ include "common.instance" . }}
{{- end -}}
{{- end -}}